# Generated by Django 4.1.13 on 2024-04-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_email_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
