/**
 * @fileoverview Generates the cached photo pool (src/photos.data.ts).
 *
 * Fetches a batch of neutral, metadata-rich photos per catalog country from the
 * Unsplash Search API, then writes them as `PHOTO_POOL`. Both the country signatures
 * and the Travel feed serve from this committed pool, so the running app makes ~zero
 * Unsplash calls (no rate-limit pressure).
 *
 * Run once (and whenever the catalog changes), with a key configured:
 *   UNSPLASH_ACCESS_KEY=... npm run build:photos
 *
 * Honors the rate limit by spacing requests; uses landscape orientation and the
 * country's search term. Re-run sparingly.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { COUNTRIES } from '../src/countries';
import { config } from '../src/config';
import type { CachedPhoto } from '../src/photos.types';

// Env-configurable so a small pool can be built locally (demo mode, 50 req/hr)
// without burning quota, and the full pool built once for the live demo:
//   PHOTOS_MAX_COUNTRIES=8 PHOTOS_PER_COUNTRY=6 npm run build:photos   # local
//   npm run build:photos                                               # full
/** Photos to fetch per country (more = steadier signatures, more API calls). */
const PER_COUNTRY = Number(process.env.PHOTOS_PER_COUNTRY ?? 12);
/** How many catalog countries to fetch (default: all). Each is one API call. */
const MAX_COUNTRIES = Number(process.env.PHOTOS_MAX_COUNTRIES ?? Number.MAX_SAFE_INTEGER);
/** Delay between API calls (ms). Demo mode (50/hr) needs ≥72000; production (5000/hr) ~800. */
const THROTTLE_MS = Number(process.env.PHOTOS_THROTTLE_MS ?? 1500);

interface SearchPhoto {
  urls: { regular: string };
  user: { name: string; links: { html: string } };
  links: { html: string; download_location: string };
  tags?: { title: string }[];
  color?: string;
}

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

async function fetchCountry(searchTerm: string, key: string): Promise<SearchPhoto[]> {
  const url = new URL('https://api.unsplash.com/search/photos');
  url.searchParams.set('query', searchTerm);
  url.searchParams.set('orientation', 'landscape');
  url.searchParams.set('content_filter', 'high');
  url.searchParams.set('per_page', String(PER_COUNTRY));
  const res = await fetch(url, { headers: { Authorization: `Client-ID ${key}` } });
  if (!res.ok)
    throw new Error(`Unsplash search failed (${String(res.status)}) for "${searchTerm}"`);
  const body = (await res.json()) as { results: SearchPhoto[] };
  return body.results;
}

async function main(): Promise<void> {
  const key = config.unsplashAccessKey;
  if (!key) throw new Error('UNSPLASH_ACCESS_KEY is required to build the photo pool.');

  const targets = COUNTRIES.slice(0, MAX_COUNTRIES);
  const pool: Record<string, CachedPhoto[]> = {};
  for (const country of targets) {
    try {
      const results = await fetchCountry(country.searchTerm, key);
      pool[country.code] = results.map((p) => ({
        country: country.code,
        imageUrl: p.urls.regular,
        attribution: `Photo by ${p.user.name} on Unsplash`,
        photographerName: p.user.name,
        photographerUrl: p.user.links.html,
        unsplashUrl: p.links.html,
        tags: p.tags?.map((t) => t.title).filter(Boolean) ?? [],
        color: p.color,
        downloadLocation: p.links.download_location,
      }));
      console.log(`${country.code}: ${String(pool[country.code]?.length ?? 0)} photos`);
    } catch (err) {
      const msg = (err as Error).message;
      console.error(`${country.code}: ${msg}`);
      // Rate limit reached — stop and write what we have rather than 403-looping.
      if (msg.includes('403')) {
        console.error('Rate limit reached — stopping early; writing the partial pool.');
        break;
      }
      pool[country.code] = [];
    }
    await sleep(THROTTLE_MS);
  }

  const header =
    '/**\n' +
    ' * @fileoverview Precomputed per-country photo pool — GENERATED by\n' +
    ' * `npm run build:photos`. Do not edit by hand.\n' +
    ' */\n\n' +
    "import type { CachedPhoto } from './photos.types';\n\n" +
    'export const PHOTO_POOL: Record<string, CachedPhoto[]> = ';
  const out = `${header}${JSON.stringify(pool, null, 2)};\n`;
  const outputPath = join(import.meta.dirname, '..', 'src', 'photos.data.ts');
  writeFileSync(outputPath, out);
  const total = Object.values(pool).reduce((n, ps) => n + ps.length, 0);
  console.log(
    `Wrote ${outputPath} — ${String(total)} photos across ${String(COUNTRIES.length)} countries`,
  );
}

void main();
