/**
 * @fileoverview The country catalog — static server-side config.
 *
 * Each country has a stable `code` (ISO 3166-1 alpha-2), a display `name`, and a
 * neutral Unsplash `searchTerm`. Search terms are **templated and landmark-free**
 * (`"<name> landscape nature scenery"`) on purpose: the demo infers preference from
 * abstract scenery, not from recognizable landmarks (see TravelPage/plan §1b). Weak
 * results for obscure entries are dropped by the photo-pool quality guardrail.
 *
 * This is just data — per-user preferences key off `code`, so reordering or extending
 * never breaks stored data. Covers UN members + observers + common territories the
 * world map renders.
 */

export interface Country {
  /** ISO 3166-1 alpha-2 code — the stable key for preferences. */
  code: string;
  /** Human-readable country name. */
  name: string;
  /** Query string sent to the Unsplash photo search. */
  searchTerm: string;
}

/** Neutral, landmark-free search term for a place. */
const term = (name: string): string => `${name} landscape nature scenery`;

// [code, name] tuples — grouped by region. searchTerm is templated from the name.
const CATALOG: readonly [string, string][] = [
  // ── Africa ────────────────────────────────────────────────────────────
  ['DZ', 'Algeria'],
  ['AO', 'Angola'],
  ['BJ', 'Benin'],
  ['BW', 'Botswana'],
  ['BF', 'Burkina Faso'],
  ['BI', 'Burundi'],
  ['CV', 'Cabo Verde'],
  ['CM', 'Cameroon'],
  ['CF', 'Central African Republic'],
  ['TD', 'Chad'],
  ['KM', 'Comoros'],
  ['CG', 'Republic of the Congo'],
  ['CD', 'DR Congo'],
  ['CI', "Côte d'Ivoire"],
  ['DJ', 'Djibouti'],
  ['EG', 'Egypt'],
  ['GQ', 'Equatorial Guinea'],
  ['ER', 'Eritrea'],
  ['SZ', 'Eswatini'],
  ['ET', 'Ethiopia'],
  ['GA', 'Gabon'],
  ['GM', 'Gambia'],
  ['GH', 'Ghana'],
  ['GN', 'Guinea'],
  ['GW', 'Guinea-Bissau'],
  ['KE', 'Kenya'],
  ['LS', 'Lesotho'],
  ['LR', 'Liberia'],
  ['LY', 'Libya'],
  ['MG', 'Madagascar'],
  ['MW', 'Malawi'],
  ['ML', 'Mali'],
  ['MR', 'Mauritania'],
  ['MU', 'Mauritius'],
  ['MA', 'Morocco'],
  ['MZ', 'Mozambique'],
  ['NA', 'Namibia'],
  ['NE', 'Niger'],
  ['NG', 'Nigeria'],
  ['RW', 'Rwanda'],
  ['ST', 'São Tomé and Príncipe'],
  ['SN', 'Senegal'],
  ['SC', 'Seychelles'],
  ['SL', 'Sierra Leone'],
  ['SO', 'Somalia'],
  ['ZA', 'South Africa'],
  ['SS', 'South Sudan'],
  ['SD', 'Sudan'],
  ['TZ', 'Tanzania'],
  ['TG', 'Togo'],
  ['TN', 'Tunisia'],
  ['UG', 'Uganda'],
  ['ZM', 'Zambia'],
  ['ZW', 'Zimbabwe'],

  // ── Americas ──────────────────────────────────────────────────────────
  ['AG', 'Antigua and Barbuda'],
  ['AR', 'Argentina'],
  ['BS', 'Bahamas'],
  ['BB', 'Barbados'],
  ['BZ', 'Belize'],
  ['BO', 'Bolivia'],
  ['BR', 'Brazil'],
  ['CA', 'Canada'],
  ['CL', 'Chile'],
  ['CO', 'Colombia'],
  ['CR', 'Costa Rica'],
  ['CU', 'Cuba'],
  ['DM', 'Dominica'],
  ['DO', 'Dominican Republic'],
  ['EC', 'Ecuador'],
  ['SV', 'El Salvador'],
  ['GD', 'Grenada'],
  ['GT', 'Guatemala'],
  ['GY', 'Guyana'],
  ['HT', 'Haiti'],
  ['HN', 'Honduras'],
  ['JM', 'Jamaica'],
  ['MX', 'Mexico'],
  ['NI', 'Nicaragua'],
  ['PA', 'Panama'],
  ['PY', 'Paraguay'],
  ['PE', 'Peru'],
  ['KN', 'Saint Kitts and Nevis'],
  ['LC', 'Saint Lucia'],
  ['VC', 'Saint Vincent and the Grenadines'],
  ['SR', 'Suriname'],
  ['TT', 'Trinidad and Tobago'],
  ['US', 'United States'],
  ['UY', 'Uruguay'],
  ['VE', 'Venezuela'],

  // ── Asia ──────────────────────────────────────────────────────────────
  ['AF', 'Afghanistan'],
  ['AM', 'Armenia'],
  ['AZ', 'Azerbaijan'],
  ['BH', 'Bahrain'],
  ['BD', 'Bangladesh'],
  ['BT', 'Bhutan'],
  ['BN', 'Brunei'],
  ['KH', 'Cambodia'],
  ['CN', 'China'],
  ['CY', 'Cyprus'],
  ['GE', 'Georgia'],
  ['IN', 'India'],
  ['ID', 'Indonesia'],
  ['IR', 'Iran'],
  ['IQ', 'Iraq'],
  ['IL', 'Israel'],
  ['JP', 'Japan'],
  ['JO', 'Jordan'],
  ['KZ', 'Kazakhstan'],
  ['KW', 'Kuwait'],
  ['KG', 'Kyrgyzstan'],
  ['LA', 'Laos'],
  ['LB', 'Lebanon'],
  ['MY', 'Malaysia'],
  ['MV', 'Maldives'],
  ['MN', 'Mongolia'],
  ['MM', 'Myanmar'],
  ['NP', 'Nepal'],
  ['KP', 'North Korea'],
  ['OM', 'Oman'],
  ['PK', 'Pakistan'],
  ['PS', 'Palestine'],
  ['PH', 'Philippines'],
  ['QA', 'Qatar'],
  ['SA', 'Saudi Arabia'],
  ['SG', 'Singapore'],
  ['KR', 'South Korea'],
  ['LK', 'Sri Lanka'],
  ['SY', 'Syria'],
  ['TW', 'Taiwan'],
  ['TJ', 'Tajikistan'],
  ['TH', 'Thailand'],
  ['TL', 'Timor-Leste'],
  ['TR', 'Turkey'],
  ['TM', 'Turkmenistan'],
  ['AE', 'United Arab Emirates'],
  ['UZ', 'Uzbekistan'],
  ['VN', 'Vietnam'],
  ['YE', 'Yemen'],

  // ── Europe ────────────────────────────────────────────────────────────
  ['AL', 'Albania'],
  ['AD', 'Andorra'],
  ['AT', 'Austria'],
  ['BY', 'Belarus'],
  ['BE', 'Belgium'],
  ['BA', 'Bosnia and Herzegovina'],
  ['BG', 'Bulgaria'],
  ['HR', 'Croatia'],
  ['CZ', 'Czechia'],
  ['DK', 'Denmark'],
  ['EE', 'Estonia'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['DE', 'Germany'],
  ['GR', 'Greece'],
  ['HU', 'Hungary'],
  ['IS', 'Iceland'],
  ['IE', 'Ireland'],
  ['IT', 'Italy'],
  ['XK', 'Kosovo'],
  ['LV', 'Latvia'],
  ['LI', 'Liechtenstein'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['MT', 'Malta'],
  ['MD', 'Moldova'],
  ['MC', 'Monaco'],
  ['ME', 'Montenegro'],
  ['NL', 'Netherlands'],
  ['MK', 'North Macedonia'],
  ['NO', 'Norway'],
  ['PL', 'Poland'],
  ['PT', 'Portugal'],
  ['RO', 'Romania'],
  ['RU', 'Russia'],
  ['SM', 'San Marino'],
  ['RS', 'Serbia'],
  ['SK', 'Slovakia'],
  ['SI', 'Slovenia'],
  ['ES', 'Spain'],
  ['SE', 'Sweden'],
  ['CH', 'Switzerland'],
  ['UA', 'Ukraine'],
  ['GB', 'United Kingdom'],
  ['VA', 'Vatican City'],

  // ── Oceania ───────────────────────────────────────────────────────────
  ['AU', 'Australia'],
  ['FJ', 'Fiji'],
  ['KI', 'Kiribati'],
  ['MH', 'Marshall Islands'],
  ['FM', 'Micronesia'],
  ['NR', 'Nauru'],
  ['NZ', 'New Zealand'],
  ['PW', 'Palau'],
  ['PG', 'Papua New Guinea'],
  ['WS', 'Samoa'],
  ['SB', 'Solomon Islands'],
  ['TO', 'Tonga'],
  ['TV', 'Tuvalu'],
  ['VU', 'Vanuatu'],

  // ── Territories & dependencies (commonly rendered on the world map) ─────
  ['GL', 'Greenland'],
  ['HK', 'Hong Kong'],
  ['MO', 'Macau'],
  ['PR', 'Puerto Rico'],
  ['EH', 'Western Sahara'],
  ['FO', 'Faroe Islands'],
  ['GI', 'Gibraltar'],
  ['PF', 'French Polynesia'],
  ['NC', 'New Caledonia'],
  ['RE', 'Réunion'],
  ['GU', 'Guam'],
  ['BM', 'Bermuda'],
  ['KY', 'Cayman Islands'],
  ['AW', 'Aruba'],
  ['CW', 'Curaçao'],
  ['GF', 'French Guiana'],
  ['MQ', 'Martinique'],
  ['GP', 'Guadeloupe'],
  ['IM', 'Isle of Man'],
  ['JE', 'Jersey'],
  ['CK', 'Cook Islands'],
  ['VG', 'British Virgin Islands'],
  ['VI', 'U.S. Virgin Islands'],
  ['TC', 'Turks and Caicos Islands'],
  ['AI', 'Anguilla'],
  ['MS', 'Montserrat'],
  ['FK', 'Falkland Islands'],
  ['AS', 'American Samoa'],
  ['MP', 'Northern Mariana Islands'],
  ['YT', 'Mayotte'],
  ['AX', 'Åland Islands'],
];

/** The full catalog — every entry gets a neutral, landmark-free search term. */
export const COUNTRIES: readonly Country[] = CATALOG.map(([code, name]) => ({
  code,
  name,
  searchTerm: term(name),
}));

/** Fast lookup by country code. */
export const COUNTRY_BY_CODE: ReadonlyMap<string, Country> = new Map(
  COUNTRIES.map((c) => [c.code, c]),
);

/** True if a code exists in the catalog. */
export function isValidCountryCode(code: string): boolean {
  return COUNTRY_BY_CODE.has(code);
}
