# Generated by Django 4.1.13 on 2024-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
