# Generated by Django 4.1.13 on 2024-04-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_testmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='backend_customuser',
        ),
    ]
